# This file is used to configure travis-ci build
os :
  - linux
  - osx

language: C
sudo: true

compiler:
  - clang
  - gcc

matrix:
  exclude:
      - os: osx
        compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - git
      - autotools-dev
      - wget

script :
  - git clone https://github.com/matteyeux/libcpuid && cd libcpuid && ./autogen.sh && sudo make install 
  - cd ../ && make # Leaving libcpuid directory
  - ./sysnet -a

notifications:
  slack: racletteteam:OmAVC9pxpO7jpkoUR9HICnYS
