# This file is used to configure travis-ci build
os :
  - linux
  - osx

language: C
sudo: true

compiler:
  - clang
  - gcc

matrix:
  exclude:
      - os: osx
        compiler: gcc
        
script : 
  - ./scripts/travis-tests.sh 

notifications:
slack: racletteteam:OmAVC9pxpO7jpkoUR9HICnYS
