# This file is used to configure travis-ci build
os :
  - linux

dist: trusty
sudo: required

language: C

compiler:
  - clang
  - gcc

before_script : 
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install libiw-dev; fi

script : 
  - ./scripts/travis-tests.sh 

notifications:
    slack: racletteteam:AoVBxu943PS49TvYlhGGjXS9
