# This file is used to configure travis-ci build
os :
  - linux
  - osx

dist: trusty
sudo: required

language: C

compiler:
  - clang
  - gcc

matrix:
  exclude:
      - os: osx
        compiler: gcc
        
before_script : 
  - sudo apt-get install libiw-dev

script : 
  - ./scripts/travis-tests.sh 

notifications:
    slack: racletteteam:AoVBxu943PS49TvYlhGGjXS9
