# This file is used to configure travis-ci build
os :
  - linux

dist: trusty
sudo: required

language: C

compiler:
  - clang
  - gcc

script : 
  - ./scripts/travis-tests.sh 

notifications:
    slack: racletteteam:AoVBxu943PS49TvYlhGGjXS9
