# This file is used to configure travis-ci build
os :
  - linux
  - osx

dist: trusty
sudo: required

language: C

compiler:
  - clang
  - gcc

matrix:
  exclude:
      - os: osx
        compiler: gcc
        
script : 
  - ./scripts/travis-tests.sh 

notifications:
slack: racletteteam:yNr1RLBfL0oAqMSo1GwJKTiD
