# This file is used to configure travis-ci build
os :
  - linux
  - osx

language: C
sudo: false

compiler:
  - clang
  - gcc

matrix:
  exclude:
      - os: osx
        compiler: gcc
        
script : 
  - make 
  - ./sysnet -a

notifications:
  slack: racletteteam:OmAVC9pxpO7jpkoUR9HICnYS
